#!/bin/bash
[ $# -eq 0 ] && { echo "Give me a mode (eg: \"./run 3\")"; exit 1; }
rosmake charles &&
    {
	export ROS_VOICE=/home/human/ros_workspace/voice_recog/src/       
    export ROS_FACE=/home/human/ros_workspace/RobotFace/node/
	xterm -geometry +0+0 -e "bash & roslaunch kinect_follower kinect_follower.launch; bash" &
	xterm -geometry +0-0 -e "bash & rosrun pocketsphinx recognizer.py; bash" &
	xterm -geometry -0-0 -e "bash & rosrun ros_speech_engine ros_speech_engine.py; bash" & 
    xterm -geometry +500+500 -e "bash & rosrun ROSFace ROSFace.py; bash" &
	xterm -geometry -0+0 -e "bash & rosrun printListener printListener & 
                                    rosrun controlnode controlnode $1; bash"
    }

